# Generated by Django 5.2.1 on 2025-06-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions_image',
            field=models.ImageField(blank=True, help_text='Imagen que muestra las medidas y dimensiones específicas del producto.', null=True, upload_to='products/dimensions_images/', verbose_name='Imagen de Medidas'),
        ),
    ]
