# Generated by Django 5.2.1 on 2025-06-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_dimensions_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['product', 'specification_type__id'], 'verbose_name': 'Especificación de Producto', 'verbose_name_plural': 'Especificaciones de Productos'},
        ),
        migrations.AlterModelOptions(
            name='specificationtype',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de Especificación de Producto', 'verbose_name_plural': 'Tipos de Especificaciones de Producto'},
        ),
    ]
